### ISSUE TITLE
Demo does not work due to library loaded via HTTP

### ISSUE THREAD

**Issue by gregorwolf** [dougalcampbell/LEDStrip#3]
Unfortunately the Demo at:
https://dougalcampbell.github.io/LEDStrip/
doesn't work as JQuery is loaded from
http://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.1/jquery.js
instead of
https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.1/jquery.js

**Comment by dougalcampbell** [comment]
Fixed. Made the jQuery URL schemeless.
